dist: trusty
sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_install:
  - composer self-update

install: travis_retry composer update --prefer-dist

script:
  - ./vendor/bin/phpunit -v --bootstrap vendor/autoload.php --testdox

cache:
  directories:
    - $HOME/.composer/cache
